In [1]:
import pandas as pd
df = pd.read_csv('./InputData/winemag-data-130k-v2.csv')
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [2]:
df.drop(df.columns[[0]], axis=1, inplace=True) # ditch that unnamed row numbers column
df.describe(include='all')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
count,129908,129971,92506,129971.000000,120975.000000,129908,108724,50511,103727,98758,129971,129970,129971
unique,43,119955,37979,NaN,NaN,425,1229,17,19,15,118840,707,16757
top,US,"Ripe plum, game, truffle, leather and menthol ...",Reserve,NaN,NaN,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,Pinot Noir,Wines & Winemakers
freq,54504,3,2009,NaN,NaN,36247,4480,11065,25514,25514,11,13272,222
mean,NaN,NaN,NaN,88.447138,35.363389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,3.039730,41.022218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,80.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,86.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,88.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,91.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,100.000000,3300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
varieties =  df['variety'].value_counts()
varieties

Pinot Noir                      13272
Chardonnay                      11753
Cabernet Sauvignon               9472
Red Blend                        8946
Bordeaux-style Red Blend         6915
Riesling                         5189
Sauvignon Blanc                  4967
Syrah                            4142
Rosé                             3564
Merlot                           3102
Nebbiolo                         2804
Zinfandel                        2714
Sangiovese                       2707
Malbec                           2652
Portuguese Red                   2466
White Blend                      2360
Sparkling Blend                  2153
Tempranillo                      1810
Rhône-style Red Blend            1471
Pinot Gris                       1455
Champagne Blend                  1396
Cabernet Franc                   1353
Grüner Veltliner                 1345
Portuguese White                 1159
Bordeaux-style White Blend       1066
Pinot Grigio                     1052
Gamay                            1025
Gewürztraminer                   1012
Viognier                          996
Shiraz                            836
                                ...
Viognier-Valdiguié                  1
Tsolikouri                          1
Pinotage-Merlot                     1
Kotsifali                           1
Barbera-Nebbiolo                    1
Jampal                              1
Tinta Madeira                       1
Syrah-Bonarda                       1
Ondenc                              1
Carcajolu                           1
Vermentino Nero                     1
Merlot-Shiraz                       1
Orangetraube                        1
Chardonnay-Pinot Gris               1
Ojaleshi                            1
Babosa Negro                        1
Teroldego Rotaliano                 1
Syrah-Malbec                        1
Ramisco                             1
Tsapournakos                        1
Cercial                             1
Maria Gomes-Bical                   1
Vranac                              1
Petit Meslier                       1
Sauvignon-Sémillon                  1
Gelber Traminer                     1
Pinot Grigio-Sauvignon Blanc        1
Tamianka                            1
Gamza                               1
Molinara                            1
Name: variety, Length: 707, dtype: int64

In [4]:
varieties.describe()

count      707.000000
mean       183.833098
std        976.188990
min          1.000000
25%          2.000000
50%          6.000000
75%         28.500000
max      13272.000000
Name: variety, dtype: float64

In [5]:
top_wines_df =  df.loc[ df['variety'].isin(varieties.axes[0][:20])] # first column[0],  rows :20  
top_wines_df['variety'].describe()

count          93914
unique            20
top       Pinot Noir
freq           13272
Name: variety, dtype: object

In [6]:
top_wines_df['variety']

0                      White Blend
1                   Portuguese Red
2                       Pinot Gris
3                         Riesling
4                       Pinot Noir
9                       Pinot Gris
10              Cabernet Sauvignon
12              Cabernet Sauvignon
14                      Chardonnay
15                        Riesling
16                          Malbec
17                          Malbec
20                       Red Blend
21                      Pinot Noir
22                     White Blend
23                          Merlot
25                      Pinot Noir
26                     White Blend
28                       Red Blend
31                       Red Blend
32                     White Blend
33                       Red Blend
34                 Sauvignon Blanc
35                      Pinot Noir
37              Cabernet Sauvignon
41                      Pinot Noir
43                 Sauvignon Blanc
44                          Merlot
45                       Red Blend
47                        Riesling
                    ...
129926                       Syrah
129928                   Red Blend
129931                  Pinot Noir
129932                   Red Blend
129933                 White Blend
129935                       Syrah
129936                  Pinot Noir
129938                      Malbec
129939                 White Blend
129940                  Chardonnay
129941                  Chardonnay
129942          Cabernet Sauvignon
129943                   Red Blend
129946                    Riesling
129947                   Red Blend
129948                      Malbec
129949                  Chardonnay
129950                   Zinfandel
129952                   Zinfandel
129954                  Pinot Gris
129955                  Chardonnay
129956    Bordeaux-style Red Blend
129958    Bordeaux-style Red Blend
129959                  Pinot Gris
129960                  Pinot Noir
129963          Cabernet Sauvignon
129965                  Pinot Gris
129966                    Riesling
129967                  Pinot Noir
129969                  Pinot Gris
Name: variety, Length: 93914, dtype: object

In [23]:
# our labels, as numbers. 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
target = le.fit_transform(top_wines_df['variety'])
len(target) #93914
target

array([18,  8,  6, ..., 11,  7,  6])

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
data = vect.fit_transform(top_wines_df['description'])
data

<93914x27105 sparse matrix of type '<class 'numpy.float64'>'
	with 3261558 stored elements in Compressed Sparse Row format>

# DecisionTreeClassifier

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target)

In [45]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.5879722305038545

# RandomForestClassifier

In [48]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.69504663742067374